GET http://localhost:3000

###

GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/1

###

POST http://localhost:3000/songs
Content-Type: application/json

{
"title": "Lasting Lover",
"artists": ["Siagla"],
"releasedDate" : "2022-07-29 00:00:00",
"duration" :"02:34"
}

###